name: restart
description: "A Flutter plugin to restart the application. The plugin works by restarting the Flutter Engine, instead of the underlying native application."
version: 1.0.2+3
homepage: https://github.com/farmako/flutter_restart
repository: https://github.com/farmako/flutter_restart

topics:
  - restart

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: app.farmako.restart
        pluginClass: RestartPlugin
      ios:
        pluginClass: RestartPlugin
